/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

/**
 *
 * @author Edison
 */
public class VentanaListarArchivos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListarArchivos
     */
    private String rutaDirectorio;
    private int controlador;
    private ActionEvent evt;

    public VentanaListarArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOcultos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDirectorio = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        txtRuta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLRuta = new javax.swing.JLabel();
        jLModificacion = new javax.swing.JLabel();
        jLTamaño = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCrear = new javax.swing.JMenu();
        jmiCrearArchivo = new javax.swing.JMenuItem();
        jmiNuevaCarpeta = new javax.swing.JMenuItem();
        jmiRenombrar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListOcultos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListOcultosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListOcultos);

        jListDirectorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDirectorioMouseClicked(evt);
            }
        });
        jListDirectorio.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDirectorioValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListDirectorio);

        jListArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListArchivosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListArchivos);

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20))
        );

        jLabel4.setText("Directorios");

        jLabel5.setText("Archivos");

        jLabel6.setText("Ocultos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLRuta.setText("RutaAbsoluta");
        jLRuta.setToolTipText("");

        jLModificacion.setText("UltimaModificacion");

        jLTamaño.setText("TamañoEnkilobites");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jLTamaño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLRuta)
                .addGap(18, 18, 18)
                .addComponent(jLModificacion)
                .addGap(18, 18, 18)
                .addComponent(jLTamaño)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jmCrear.setText("Archivo");

        jmiCrearArchivo.setText("CrearArchivo");
        jmiCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCrearArchivoActionPerformed(evt);
            }
        });
        jmCrear.add(jmiCrearArchivo);

        jmiNuevaCarpeta.setText("NuevaCarpeta");
        jmiNuevaCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaCarpetaActionPerformed(evt);
            }
        });
        jmCrear.add(jmiNuevaCarpeta);

        jmiRenombrar.setText("Renombrar");
        jmiRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRenombrarActionPerformed(evt);
            }
        });
        jmCrear.add(jmiRenombrar);

        jmiEliminar.setText("Eliminar");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jmCrear.add(jmiEliminar);

        jMenuBar1.add(jmCrear);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.evt = evt;
        if (! txtRuta.getText().equals("")) {
            File ruta = new File(txtRuta.getText());
            File[] archivos = ruta.listFiles();
            DefaultListModel model = new DefaultListModel();
            for (File archivo : archivos) {
                if (archivo.isDirectory()) {
                    model.addElement(archivo.getName());
                }
            }
            jListDirectorio.setModel(model);
            model = new DefaultListModel();
            for (File archivo : archivos) {
                if (archivo.isFile() && !archivo.isHidden()) {
                    model.addElement(archivo.getName());
                }
            }
            jListArchivos.setModel(model);
            model = new DefaultListModel();
            for (File archivo : archivos) {
                if (archivo.isHidden()) {
                    model.addElement(archivo.getName());
                }
            }
            jListOcultos.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jListDirectorioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDirectorioValueChanged
        controlador = 1;
        String elementoSelecionado = (String) jListDirectorio.getSelectedValue();
        String rutaselecionada = txtRuta.getText().trim() + "\\" + elementoSelecionado;
        rutaDirectorio = rutaselecionada;
        File fichero = new File(rutaselecionada);
        long fechaMilisegundos = fichero.lastModified();
        Date fecha = new Date(fechaMilisegundos);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText("" + fichero.length() / 1024);
        jListArchivos.clearSelection();
        jListOcultos.clearSelection();
    }//GEN-LAST:event_jListDirectorioValueChanged

    private void jListArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListArchivosValueChanged
        controlador = 0;
        String elementoSelecionado = (String) jListArchivos.getSelectedValue();
        String rutaselecionada = txtRuta.getText().trim() + "\\" + elementoSelecionado;
        File fichero = new File(rutaselecionada);
        long fechaMilisegundos = fichero.lastModified();
        Date fecha = new Date(fechaMilisegundos);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText("" + fichero.length() / 1024);
        jListDirectorio.clearSelection();
        jListOcultos.clearSelection();
    }//GEN-LAST:event_jListArchivosValueChanged

    private void jListOcultosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListOcultosValueChanged
        controlador = 0;
        String elementoSelecionado = (String) jListOcultos.getSelectedValue();
        String rutaselecionada = txtRuta.getText().trim() + "\\" + elementoSelecionado;
        File fichero = new File(rutaselecionada);
        long fechaMilisegundos = fichero.lastModified();
        Date fecha = new Date(fechaMilisegundos);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLModificacion.setText(formato.format(fecha));
        jLRuta.setText(fichero.getAbsolutePath());
        jLTamaño.setText("" + fichero.length() / 1024);
        jListArchivos.clearSelection();
        jListDirectorio.clearSelection();
    }//GEN-LAST:event_jListOcultosValueChanged

    private void jmiCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCrearArchivoActionPerformed
        String nombre = JOptionPane.showInputDialog("Crear Fichero");
        String ruta;
        if (controlador == 0) {
            ruta = txtRuta.getText() + "\\" + nombre;

        } else {
            ruta = rutaDirectorio + "\\" + nombre;
        }
        File archivoNuevo = new File(ruta);
        if (!archivoNuevo.exists()) {
            try {
                archivoNuevo.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "no se pudo crar el archivo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El archivo ya existe");
        }
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jmiCrearArchivoActionPerformed

    private void jmiRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRenombrarActionPerformed
        String archivoSelecionado = null;
        if (!jListDirectorio.isSelectionEmpty()) {
            archivoSelecionado = (String) jListDirectorio.getSelectedValue();
        } else if (!jListArchivos.isSelectionEmpty()) {
            archivoSelecionado = (String) jListArchivos.getSelectedValue();
        } else if (!jListOcultos.isSelectionEmpty()) {
            archivoSelecionado = (String) jListOcultos.getSelectedValue();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione");
        }
        String rutaArchivoSelecionado = txtRuta.getText().trim() + "\\" + archivoSelecionado;
        File archivo = new File(rutaArchivoSelecionado);

        String nombreNuevoArchivo = JOptionPane.showInputDialog("Ingresa el nuevo nombre del archivo");
        String rutaNuevoArchivo = txtRuta.getText().trim() + "\\" + nombreNuevoArchivo;
        File archivoNuevo = new File(rutaNuevoArchivo);

        if (!archivoNuevo.exists()) {
            archivo.renameTo(archivoNuevo);
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre");
        }
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jmiRenombrarActionPerformed

    private void jmiNuevaCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaCarpetaActionPerformed
        String nombre = JOptionPane.showInputDialog("Crear Fichero");
        String ruta;
        if (controlador == 0) {
            ruta = txtRuta.getText() + "\\" + nombre;

        } else {
            ruta = rutaDirectorio + "\\" + nombre;
        }
        File archivoNuevo = new File(ruta);
        if (!archivoNuevo.exists()) {
            archivoNuevo.mkdir();
        } else {
            JOptionPane.showMessageDialog(this, "El archivo ya existe");
        }
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jmiNuevaCarpetaActionPerformed

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        String archivoSelecionado = null;
        boolean isValid = true;
        if (!jListDirectorio.isSelectionEmpty()) {
            archivoSelecionado = (String) jListDirectorio.getSelectedValue();
        } else if (!jListArchivos.isSelectionEmpty()) {
            archivoSelecionado = (String) jListArchivos.getSelectedValue();
        } else if (!jListOcultos.isSelectionEmpty()) {
            archivoSelecionado = (String) jListOcultos.getSelectedValue();
        } else {
            isValid = false;
            JOptionPane.showMessageDialog(this, "Selecione");
        }
        if (isValid) {
            String rutaArchivoSelecionado = txtRuta.getText().trim() + "\\" + archivoSelecionado;
            File archivo = new File(rutaArchivoSelecionado);
            if(archivo.isDirectory()){
                eliminarCarpeta(rutaArchivoSelecionado);
            }else{
                archivo.delete();
            }           
            btnBuscarActionPerformed(evt);
        }
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void jListDirectorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDirectorioMouseClicked
        if(evt.getClickCount()==2){
            String archivoSelecionado = (String) jListDirectorio.getSelectedValue();
            txtRuta.setText(txtRuta.getText()+"\\"+archivoSelecionado);
            btnBuscarActionPerformed(this.evt);
        }
    }//GEN-LAST:event_jListDirectorioMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        String nuevaRuta = null;
        for (int i = txtRuta.getText().length()-1; i >= 0 ; i--) {
            if(txtRuta.getText().charAt(i) == '\\'){
                nuevaRuta = txtRuta.getText().substring(0, i);
                System.out.println(nuevaRuta);
                i = -1;
            }
        }
        txtRuta.setText(nuevaRuta);
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void eliminarCarpeta(String ruta){
        File lista = new File(ruta);
        File[]archivos = lista.listFiles();
        for (File archivo : archivos) {
            if(archivo.isDirectory()){
                eliminarCarpeta(ruta+"\\"+archivo.getName());
            }else{
                archivo.delete();
            }
        }
        lista.delete();
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListarArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListarArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLModificacion;
    private javax.swing.JLabel jLRuta;
    private javax.swing.JLabel jLTamaño;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JList<String> jListDirectorio;
    private javax.swing.JList<String> jListOcultos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu jmCrear;
    private javax.swing.JMenuItem jmiCrearArchivo;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiNuevaCarpeta;
    private javax.swing.JMenuItem jmiRenombrar;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
